"""Make personal info fields optional

Revision ID: 52f03f2189da
Revises: 854b56003e57
Create Date: 2025-07-13 03:21:09.230521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '52f03f2189da'
down_revision: Union[str, None] = '854b56003e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personalinfo', 'date_of_birth',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('personalinfo', 'blood_group',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('personalinfo', 'aadhar_no',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('personalinfo', 'personal_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('personalinfo', 'mobile_no',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('personalinfo', 'father_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('personalinfo', 'father_occupation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('personalinfo', 'father_mobile',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('personalinfo', 'mother_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('personalinfo', 'mother_occupation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('personalinfo', 'mother_mobile',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('personalinfo', 'local_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('personalinfo', 'permanent_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('personalinfo', 'ssc',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('personalinfo', 'hsc',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('personalinfo', 'diploma',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('personalinfo', 'sport',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('personalinfo', 'other',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('personalinfo', 'photo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personalinfo', 'photo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('personalinfo', 'other',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('personalinfo', 'sport',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('personalinfo', 'diploma',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('personalinfo', 'hsc',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('personalinfo', 'ssc',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('personalinfo', 'permanent_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('personalinfo', 'local_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('personalinfo', 'mother_mobile',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('personalinfo', 'mother_occupation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('personalinfo', 'mother_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('personalinfo', 'father_mobile',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('personalinfo', 'father_occupation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('personalinfo', 'father_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('personalinfo', 'mobile_no',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('personalinfo', 'personal_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('personalinfo', 'aadhar_no',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('personalinfo', 'blood_group',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('personalinfo', 'date_of_birth',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
